name: news_flutter
packages:
  - packages/**
  - packages/app

scripts:
  sync_deps: dart tools/sync_dependencies.dart
  generate:
    run: melos exec dart run build_runner build --delete-conflicting-outputs
  rebuild:
    exec: |
      melos run sync_deps
      flutter clean
      flutter pub get
      dart run build_runner build --delete-conflicting-outputs
    description: rebuild project and generate files