name: localization
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  get: ^4.6.6
  json_annotation: ^4.9.0
  flutter_bloc: ^8.1.3
  go_router: ^13.2.0
  flutter_svg: ^2.0.10
  injectable: ^2.3.2
  get_it: ^7.7.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  logger: ^2.0.2+1
  retrofit: ">=4.0.0 <5.0.0"
  dio: ^5.5.0+1




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1
  injectable_generator: ^2.7.0
  bdd_widget_test: ^1.7.4
  analyzer: ^7.1.1
  retrofit_generator: ^9.0.0


flutter:
  generate: true
  uses-material-design: true

flutter_intl:
  enabled: true
