name: shared_pref
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  # current module dependencies
  get: ^4.6.6
  json_annotation: ^4.9.0
  shared_preferences: ^2.2.3



  # shared
  injectable: ^2.3.2
  get_it: ^7.7.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1




dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  #  flutter_gen_runner: ^5.9.0
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  analyzer: 6.11.0


flutter:
  generate: true
  uses-material-design: true

