name: navigation
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter








dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  #  flutter_gen_runner: ^5.9.0
  json_serializable: ^6.7.1
  injectable_generator: ^2.4.1
  mockito: 5.4.4
  analyzer: 6.11.0


flutter:
  generate: true
  uses-material-design: true
